### ISSUE TITLE
rgb command missing ?

### ISSUE THREAD

**Issue by Scotty-89** [iobroker-community-adapters/ioBroker.hue-extended#85]
Hallo,

ich habe nun komplett auf den Adapter umgestellt und musste feststellen das meine gesamten Command die ich verwendet habe nicht mehr gehen :(

es gibt immer eine Fehlermeldung beim setzten von rgb 
Probiert habe ich:
{"on":true,"rgb":"255,0,0","level":50}
{"on":true,"rgb":"[255,0,0]","level":50}
{"on":true,"rgb":"[255,0,0]","level":50}
{"on":true,"_rgb":"255,0,0","level":50}
{"on":true,"_rgb":"[255,0,0]","level":50}
{"on":true,"_rgb":"[255,0,0]","level":50}

also meldung erhalte ich immer 
8843) Attempt 1x - Error setting /lights/14/state/_rgb: parameter, _rgb, not available
bzw. 8843) Attempt 1x - Error setting /lights/14/state/_rgb: parameter, rgb, not available

bin ich zu doof oder ist es wirklich ein Problem ? habe ein Eintrag von 2019 gefunden wo es gelöst wurde, eigentlich...

**Comment by Zefau** [comment]
Wo hast du die Lösung gefunden? Code sieht tatsächlich so aus, als ginge das nicht. Wundert mich gerade selbst. Kannst du den `rgb` Datenpunkt direkt ansteuern?

**Comment by Scotty-89** [comment]
https://forum.iobroker.net/topic/24207/neuer-adapter-hue-extended/175   ;)

ja den Datenpunkt rgb kann ich manuell ändern und wird auch übernommen.

**Comment by Scotty-89** [comment]
gibt es hier was neues ?

**Comment by Gosuwaldbear** [comment]
Hallo, 
ich habe versucht über den Colorpicker von Jarvis eine HUE RGB zu schalten. Leider ohne Erfolg.
Der hue-extended stürzt mit folgender Fehlermeldung ab:

2021-01-26 07:24:32.806 - debug: hue-extended.0 (6773) Objects client ready ... initialize now
2021-01-26 07:24:32.807 - debug: hue-extended.0 (6773) Objects create System PubSub Client
2021-01-26 07:24:32.808 - debug: hue-extended.0 (6773) Objects create User PubSub Client
2021-01-26 07:24:32.808 - debug: hue-extended.0 (6773) Objects client initialize lua scripts
2021-01-26 07:24:32.817 - debug: hue-extended.0 (6773) Objects connected to redis: 127.0.0.1:9001
2021-01-26 07:24:32.819 - debug: hue-extended.0 (6773) objectDB connected
2021-01-26 07:24:32.820 - debug: hue-extended.0 (6773) Redis States: Use Redis connection: 127.0.0.1:9000
2021-01-26 07:24:32.823 - debug: hue-extended.0 (6773) States create User PubSub Client
2021-01-26 07:24:32.824 - debug: hue-extended.0 (6773) States create System PubSub Client
2021-01-26 07:24:32.828 - debug: hue-extended.0 (6773) States connected to redis: 127.0.0.1:9000
2021-01-26 07:24:32.829 - debug: hue-extended.0 (6773) statesDB connected
2021-01-26 07:24:32.960 - info: hue-extended.0 (6773) starting. Version 2.0.0 in /opt/iobroker/node_modules/iobroker.hue-extended, node: v12.20.1, js-controller: 3.1.6
2021-01-26 07:24:32.969 - info: hue-extended.0 (6773) Establishing secure connection to bridge..
2021-01-26 07:24:33.105 - info: hue-extended.0 (6773) Using polling for state updates.
2021-01-26 07:24:40.805 - debug: hue-extended.0 (6773) system.adapter.admin.0: logging false
2021-01-26 07:24:57.187 - debug: hue-extended.0 (6773) State of hue-extended.0.lights.003-stehlampe1.action.rgb has changed {"val":246,"ack":false,"ts":1611642297186,"q":0,"from":"system.adapter.web.0","user":"system.user.admin","lc":1611642297186}.
2021-01-26 07:24:57.188 - error: hue-extended.0 (6773) uncaught exception: value.split is not a function
2021-01-26 07:24:57.189 - error: hue-extended.0 (6773) TypeError: value.split is not a function
at Adapter. (/opt/iobroker/node_modules/iobroker.hue-extended/hue-extended.js:352:17)
at Adapter.emit (events.js:314:20)
at Immediate. (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5388:34)
at processImmediate (internal/timers.js:461:21)
2021-01-26 07:24:57.189 - info: hue-extended.0 (6773) Adapter stopped und unloaded.
2021-01-26 07:24:57.190 - info: hue-extended.0 (6773) terminating
2021-01-26 07:24:57.191 - info: hue-extended.0 (6773) Terminated (NO_ERROR): Without reason
2021-01-26 07:25:27.972 - debug: hue-extended.0 (6788) Redis Objects: Use Redis connection: 127.0.0.1:9001
2021-01-26 07:25:27.988 - debug: hue-extended.0 (6788) Objects client ready ... initialize now
2021-01-26 07:25:27.989 - debug: hue-extended.0 (6788) Objects create System PubSub Client
2021-01-26 07:25:27.990 - debug: hue-extended.0 (6788) Objects create User PubSub Client
2021-01-26 07:25:27.990 - debug: hue-extended.0 (6788) Objects client initialize lua scripts
2021-01-26 07:25:27.998 - debug: hue-extended.0 (6788) Objects connected to redis: 127.0.0.1:9001
2021-01-26 07:25:28.000 - debug: hue-extended.0 (6788) objectDB connected
2021-01-26 07:25:28.000 - debug: hue-extended.0 (6788) Redis States: Use Redis connection: 127.0.0.1:9000
2021-01-26 07:25:28.004 - debug: hue-extended.0 (6788) States create User PubSub Client
2021-01-26 07:25:28.005 - debug: hue-extended.0 (6788) States create System PubSub Client
2021-01-26 07:25:28.010 - debug: hue-extended.0 (6788) States connected to redis: 127.0.0.1:9000
2021-01-26 07:25:28.010 - debug: hue-extended.0 (6788) statesDB connected
2021-01-26 07:25:28.175 - info: hue-extended.0 (6788) starting. Version 2.0.0 in /opt/iobroker/node_modules/iobroker.hue-extended, node: v12.20.1, js-controller: 3.1.6
2021-01-26 07:25:28.184 - info: hue-extended.0 (6788) Establishing secure connection to bridge..
2021-01-26 07:25:28.388 - info: hue-extended.0 (6788) Using polling for state updates.

über die Objekte lässt sich die Farbe ohne Probleme einstellen.
Bin mir nicht sicher ob es an dem Hue oder Jarvis Adapter liegt.

**Comment by mcm1957** [comment]
Currently no further development isplanned for this adapter. Please use ioBroker.hue.
